[package]
name = "iota-wallet"
version = "0.1.0"
authors = ["Lucas Nogueira <lucas.nogueira@iota.org>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
thiserror = "1.0"
chrono = { version = "0.4", features = ["serde"] }
getset = "0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_repr = "0.1"
once_cell = "1.5"
iota-core = { git = "https://github.com/iotaledger/iota.rs", branch = "dev" }
url = { version = "2.2", features = [ "serde" ] }
tokio = "0.2"
rand = "0.7"
rusqlite = { version = "0.24", features = ["bundled"], optional = true }
slip10 = "0.4"
bech32 = "0.7"
hex = "0.4"
futures = "0.3"
backtrace = "0.3"

# env mnemonic
bee-signing-ext = { git = "https://github.com/wusyong/bee-p.git", branch = "sign-ext", version = "^0.1.0-alpha" }
hmac = "0.10"
blake2 = "0.9"
unicode-normalization = "0.1"
pbkdf2 = "0.6"
sha2 = "0.9"
dotenv = "0.15"
dialoguer = "0.7"
tiny-bip39 = "0.8"

# stronghold
iota-stronghold = { git = "https://github.com/iotaledger/stronghold.rs", branch = "feat/pre-refactor", optional = true }

[dev-dependencies]
tokio = { version = "0.2", features = ["full"] }
sled = "0.34"
rusty-fork = "0.3"

[features]
default = ["stronghold"]
stronghold = ["iota-stronghold", "rusqlite"]
sqlite = ["rusqlite"]
